### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by isalirezag** [yeephycho/tensorflow_input_image_by_tfrecord#1]
Thanks for the tutorial!
It is really useful.
I am using Tensorflow on windows via Python 3.6 with Anaconda.
When I run `build_image_data` I received the following error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
 
Any idea what I need to do? 

![image](https://user-images.githubusercontent.com/12434910/29432982-5637c020-8352-11e7-8491-c4e3982c8e6a.png)

Thanks!

**Comment by yeephycho** [comment]
Hi @isalirezag .
This repo. was created a long time ago, after a few times iteration of tensorflow, I am not sure whether it still can work as months earlier.

I noticed that the last line of the terminal, the program has already write 302 images into tfrecord, so my suggestion is try to validate whether the tfrecord file contains the right images and metadata.

With regards!

**Comment by isalirezag** [comment]
Thanks @yeephycho ,
I realized I had to change line of the code to

```
with tf.gfile.FastGFile(filename, 'rb') as f:
    image_data = f.read()
```
and it works now.

**Comment by shreyagurung** [comment]
it still doesnt work for me. Still showing the same error please help

**Comment by kiranbeethoju** [comment]
The best method of reading/accessing that data is by below snippet
pd.read_csv('data.csv', encoding='latin1')
in your case try to add encoding='latin1' that's it
