### ISSUE TITLE
How to create .tfrecord -file?

### ISSUE THREAD

**Issue by jannenev** [yeephycho/tensorflow_input_image_by_tfrecord#10]
I run the examples in README
"python build_image_data.py"
OK
Wrote 150 images to ./train-00000-of-00002
Wrote 150 images to ./train-00001-of-00002

Then I run next command

"python read_tfrecord_data.py --image_number=300 --class_number=3 --image_height=299 --image_width=299"
20 files were found under current folder. 
Please be noted that only files end with '*.tfrecord' will be load!
Cannot find any tfrecord files, please check the path.

How does the creation of filename.tfrecord happen?

**Comment by yeephycho** [comment]
Build_image_data.py, line 87, change the number of shard.
