### ISSUE TITLE
read_tfrecord_data.py

### ISSUE THREAD

**Issue by isn350** [yeephycho/tensorflow_input_image_by_tfrecord#11]
Hi,

I'm trying to run read_tfrecord_data.py after running build_image_data.py successfully.  read_tfrecord_data.py giving me an error message as follow:
  File "read_tfrecord_data.py", line 27
    self.image = tf.Variable([], dtype = tf.string)
                                                                        ^
TabError: inconsistent use of tabs and spaces in indentation
 
I didn't write the code nor changed it. I used clone to get the files. 

Is there any ideas on how to solve this issue.

Best,
IA

**Comment by yeephycho** [comment]
Seems caused by typo or format, you can modify the code and play around with it~
