### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by clhne** [yeephycho/tensorflow_input_image_by_tfrecord#13]
Hi, @yeephycho 
After run build_image_data.py，output two file: 
1. train-00000-of-00002
2. train-00001-of-00002
But in read_tfrecord_data.py, the file should be .tfrecord format, ie, when run:
`python read_tfrecord_data.py --image_number=300 --class_number=3 --image_height=299 --image_width=299`      

generate an error:
Please be noted that only files end with '*.tfrecord' will be load!
Cannot find any tfrecord files, please check the path.
Because it cannot find any *.tfrecord file.
Solution:
Modify the line 253 of build_image_data.py :
`output_filename = '%s-%.5d-of-%.5d' % (name, shard, num_shards)`
to 
`output_filename = '%s-%.5d-of-%.5d.tfrecord' % (name, shard, num_shards)`

**Comment by apple1987** [comment]
%s-%.5d-of-%.5d.tfrecore to %s-%.5d-of-%.5d.tfrecord

**Comment by clhne** [comment]
> %s-%.5d-of-%.5d.tfrecore to %s-%.5d-of-%.5d.tfrecord

Yeah, Thanks.

**Comment by clhne** [comment]
@yeephycho 
Hi, yeephycho
From the comment of apple1987, I believe there still somebody use your code, so I send the [pull request](https://github.com/yeephycho/tensorflow_input_image_by_tfrecord/pull/14).
