### ISSUE TITLE
Which version of Python and Tensorflow did you use?

### ISSUE THREAD

**Issue by dhbrand** [yeephycho/tensorflow_input_image_by_tfrecord#6]
Hi I'm trying to get your program to run on the sample data and I keep getting an error.  I've tried using python 3.6 with tf 1.4 and even python 3.5 with tf 0.12 but I get an error. I'm on MacOS but I can VM if I need to.

**Comment by yeephycho** [comment]
Hi @dhbrand ,
I think python 2.7 will be fine, I suppose python 3.x will also work. I cannot provide further help if I cannot see what the error is?

With regards!

Yeephycho

**Comment by dhbrand** [comment]
I’ll try it with 2.7 and 3.6 again and pair with Tensorflow 1.0 and 1.4 for each and relay the errors.  Thanks.

**Comment by dhbrand** [comment]
I

[err_py2.7_tf0.12.txt](https://github.com/yeephycho/tensorflow_input_image_by_tfrecord/files/1670293/err_py2.7_tf0.12.txt)
[err_py3.6_tf1.0.txt](https://github.com/yeephycho/tensorflow_input_image_by_tfrecord/files/1670294/err_py3.6_tf1.0.txt)

I tried a couple combinations and am getting a similar error for both.  I'm attaching the output from my terminal.

**Comment by yeephycho** [comment]
Hi @dhbrand ,
From the error text, I can obtain the following information:
1. I cannot sure whether you gave the right path to the label folder.
2. The error happens at the jpeg file decoding step, so please check your data to see whether there are corrupted image files.
3. I have no idea why "0 image was write to 49 shards", this behavior is far from my definition, follow the instruction to work the pipeline out first before you try to modify the code when you are not familiar with tensorflow.

4. This is not a version problem, so it's useless to change versions.

With thanks and regards!
Yeephycho
