### ISSUE TITLE
知识就是力量

### ISSUE THREAD

**Issue by DontsingListen** [yeephycho/tensorflow_input_image_by_tfrecord#8]
博主，你好，在src/dog文件夹下，有一个test文件，我怀着对未知事物充满好奇的心情，用激动地颤抖的手，握着鼠标，虔诚地点开了它。果然，没让我失望，屏幕赫赫出现一句：“知识就是力量”。于是，我忍不住开了这个issue。

**Comment by yeephycho** [comment]
Hi @DontsingListen ,
Thanks for your feedback and I found it's true.
Just leave with it, after all, it doesn't affect the rest part of the project.

Thanks and have a nice afternoon!

Yours Yeephycho

**Comment by DontsingListen** [comment]
haha, it's a bonus for me.

Have a nice afrernoon!
